import sound from "./sound.js";
import reviews from "./reviews-slide.js";
import hamburger from "./hamburger-menu.js";
import product from "./product.js";
import productsSlide from "./products-slide.js";
import header from "./header.js"
import theme from "./theme.js"
import notifications from "./notifications.js";
import cart from "./cart.js";